### ISSUE TITLE
e2e timeline decoration 

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#1279]
- [ ] No need to decorate encrypted messages in encrypted rooms, as users will understand this contextually from room
- [ ] Decorate unencrypted messages in e2e rooms with warning icon, to warn them this content isn't encrypted
- [ ] Decorate messages encrypted by an unverified device, from **users who are verified**

See also https://github.com/vector-im/riot-web/issues/13304

<img width="705" alt="image" src="https://user-images.githubusercontent.com/9841565/80222932-da361980-8647-11ea-9f2d-93828603297e.png">
